version: "3.8"
volumes: 
  mymariadbdata: ~
  php: ~
services:
  apache1: 
    ports: 
      - 8080:80
    image: imrxn21/deelopdracht:latest
    volumes:
      - php:/var/www/html
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=wachtwoord
    volumes: 
      - mymariadbdata:/var/lib/mysql
